image: medokin/ember-cli-test:latest

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/
    - bower_components/

stages:
  - setup
  - test

setup:
  stage: setup
  script:
    - npm install
    - bower install --allow-root
  tags:
    - docker

tests:
  stage: test
  script:
    - COVERAGE=true ember test
  tags:
    - docker
