image: medokin/ember-cli-test:latest

before_script:
  - npm install
  - bower install --allow-root


stages:
  - test

tests:
  stage: test
  variables:
    COVERAGE: true
  script:
    - ember test
  tags:
    - docker
